name = "Cosmos"
version = "0.0.3"
authors = ["Muhamad Nauval Azhar <hi@nauv.al>"]
description = "Cosmos theme for Zed"
repository = "https://github.com/nauvalazhar/cosmos"
id = "cosmos"
schema_version = 1
